(in-package "SPECIALIZATION-STORE.FEATURES")

(declaim (ftype (function (integer) (values integer integer)) test-global-function))
(defun test-global-function (a)
  (values (+ a 1) (+ a -1)))

(defun feature/function-information ()
  (flet ((test-local-function (a)
           (values (+ a -1) (+ a 1)))
         (expected-form-p (form)
           (and (listp form)
                (eql 'function (first form))
                (equal '(integer) (second form))
                (listp (third form))                
                (destructuring-bind (name first second &rest others) (third form)
                  (declare (ignore others))
                  (and (eql 'values name)
                       (eql 'integer first)
                       (eql 'integer second))))))
    (declare (ftype (function (integer) (values integer integer)) test-local-function)
             (ignorable (function test-local-function)))
    (macrolet ((compute (name &environment env)
                 (multiple-value-bind (binding-type local? declarations)
                     (introspect-environment:function-information name env)
                   (declare (ignore local?))
                   (when (eql :function binding-type)
                     `(quote ,(cdr (assoc 'ftype declarations)))))))
      (let* ((global? (expected-form-p (compute test-global-function)))
             (local? (expected-form-p (compute test-local-function))))
        (when (and global? local?)
          (pushnew 'function-declarations *features*))))))

(feature/function-information)
